# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_choose(object):
    def setupUi(self, choose):
        choose.setObjectName("choose")
        choose.resize(762, 425)
        self.verticalLayout = QtWidgets.QVBoxLayout(choose)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(choose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(choose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setStyleSheet("background-color: rgb(28, 42, 61);\n"
"color: rgb(53, 126, 165);\n"
"border:5px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(60, 72, 83);")
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        self.listWidget_2 = QtWidgets.QListWidget(choose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_2.sizePolicy().hasHeightForWidth())
        self.listWidget_2.setSizePolicy(sizePolicy)
        self.listWidget_2.setMinimumSize(QtCore.QSize(256, 0))
        self.listWidget_2.setStyleSheet("background-color: rgb(28, 42, 61);\n"
"color: rgb(53, 126, 165);\n"
"border:5px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(60, 72, 83);")
        self.listWidget_2.setObjectName("listWidget_2")
        self.horizontalLayout.addWidget(self.listWidget_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QtWidgets.QComboBox(choose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setStyleSheet("background-color: rgb(28, 42, 61);\n"
"color: rgb(53, 126, 165);\n"
"border:5px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(60, 72, 83);")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(choose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("background-color: rgb(28, 42, 61);\n"
"color: rgb(53, 126, 165);\n"
"border:5px solid;\n"
"border-radius: 10px;\n"
"border-color: rgb(60, 72, 83);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(choose)
        QtCore.QMetaObject.connectSlotsByName(choose)

    def retranslateUi(self, choose):
        _translate = QtCore.QCoreApplication.translate
        choose.setWindowTitle(_translate("choose", "Выберите серию"))
        self.label.setText(_translate("choose", "Выберите серию и озвучку:"))
        self.comboBox.setPlaceholderText(_translate("choose", "Выберите озвучку"))
        self.pushButton.setText(_translate("choose", "Смотреть!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    choose = QtWidgets.QWidget()
    ui = Ui_choose()
    ui.setupUi(choose)
    choose.show()
    sys.exit(app.exec_())
